version: 2.1
jobs:
  mariadb-103:
    # workaround https://discuss.circleci.com/t/post-clone-working-directory/15333/4
    working_directory: ~/repo/10
    machine: true
    environment:
      - ALPINE_VER: 3.9
      - BASE_IMAGE_STABILITY_TAG: 2.2.2
      - MARIADB_VER: 10.3.14
      - TAGS: 10.3,10,latest
    steps:
      - checkout:
          path: ~/repo
      - run: make
      - run: make test
      - run: . ../release.sh
#      - notify-about-failure

  mariadb-102:
    working_directory: ~/repo/10
    machine: true
    environment:
      - ALPINE_VER: 3.9
      - BASE_IMAGE_STABILITY_TAG: 2.2.2
      - MARIADB_VER: 10.2.23
      - TAGS: 10.2
    steps:
      - checkout:
          path: ~/repo
      - run: make
      - run: make test
      - run: . ../release.sh
#      - notify-about-failure

  mariadb-101:
    working_directory: ~/repo/10
    machine: true
    environment:
      - ALPINE_VER: 3.8
      - BASE_IMAGE_STABILITY_TAG: 2.2.2
      - MARIADB_VER: 10.1.38
      - TAGS: 10.1
    steps:
      - checkout:
          path: ~/repo
      - run: make
      - run: make test
      - run: . ../release.sh
#      - notify-about-failure

workflows:
  build-test-release:
    jobs:
      - mariadb-103:
          filters:
            tags:
              only: /.*/
      - mariadb-102:
          filters:
            tags:
              only: /.*/
      - mariadb-101:
          filters:
            tags:
              only: /.*/

commands:
  notify-about-failure:
    steps:
      - run:
          when: on_fail
          name: 'Notify about failure by email'
          command: |
            aws ses send-email --region us-east-1 --from robot@wodby.com --to circleci@wodby.com \
              --subject "MariaDB ${MARIADB_VER} build failed" --text "Build URL: ${CIRCLE_BUILD_URL}"