version: 2
jobs:
  mariadb-103:
    working_directory: ~/repo/10
    machine: true
    environment:
      - MARIADB_VER: 10.3.7
      - TAGS: 10.3,10,latest
    steps:
      - checkout:
          path: ~/repo
      - run: ls -la
      - run: make
      - run: make test
      - run: . "${CIRCLE_WORKING_DIRECTORY}/release.sh"

  mariadb-102:
    working_directory: ~/project/10
    machine: true
    environment:
      - MARIADB_VER: 10.2.16
      - TAGS: 10.2
    steps:
      - checkout
      - run: make
      - run: make test
      - run: . "${CIRCLE_WORKING_DIRECTORY}/release.sh"

  mariadb-101:
    working_directory: ~/project/10
    machine: true
    environment:
      - MARIADB_VER: 10.1.34
      - TAGS: 10.1
    steps:
      - checkout
      - run: make
      - run: make test
      - run: . "${CIRCLE_WORKING_DIRECTORY}/release.sh"

workflows:
  version: 2
  build_and_test:
    jobs:
      - mariadb-103:
          filters:
            tags:
              only: /.*/
      - mariadb-102:
          filters:
            tags:
              only: /.*/
      - mariadb-101:
          filters:
            tags:
              only: /.*/
