version: 2.1
jobs:
  mariadb-105:
    # workaround https://discuss.circleci.com/t/post-clone-working-directory/15333/4
    working_directory: ~/repo/10
    machine: true
    environment:
    - ALPINE_VER: 3.12
    - BASE_IMAGE_STABILITY_TAG: 2.5.1
    - MARIADB_VER: 10.5.8
    - TAGS: 10.5,10,latest
    steps:
    - checkout:
        path: ~/repo
    - run: make
    - run: make test
    - run: . ../release.sh

  mariadb-104:
    working_directory: ~/repo/10
    machine: true
    environment:
    - ALPINE_VER: 3.12
    - BASE_IMAGE_STABILITY_TAG: 2.5.1
    - MARIADB_VER: 10.4.17
    - TAGS: 10.4
    steps:
    - checkout:
        path: ~/repo
    - run: make
    - run: make test
    - run: . ../release.sh

#  mariadb-104g:
#    working_directory: ~/repo/10
#    machine: true
#    environment:
#    - ALPINE_VER: 3.12
#    - BASE_IMAGE_STABILITY_TAG: 2.5.1
#    - MARIADB_VER: 10.4.17
#    - GALERA_VER: 26.4.3
#    - TAGS: 10.4-galera,10-galera,galera
#    steps:
#    - checkout:
#        path: ~/repo
#    - run: make
#    - run: make test
#    - run: . ../release.sh

  mariadb-103:
    working_directory: ~/repo/10
    machine: true
    environment:
    - ALPINE_VER: 3.12
    - BASE_IMAGE_STABILITY_TAG: 2.5.1
    - MARIADB_VER: 10.3.26
    - TAGS: 10.3
    steps:
    - checkout:
        path: ~/repo
    - run: make
    - run: make test
    - run: . ../release.sh

  mariadb-102:
    working_directory: ~/repo/10
    machine: true
    environment:
    - ALPINE_VER: 3.12
    - BASE_IMAGE_STABILITY_TAG: 2.5.1
    - MARIADB_VER: 10.2.35
    - TAGS: 10.2
    steps:
    - checkout:
        path: ~/repo
    - run: make
    - run: make test
    - run: . ../release.sh

workflows:
  build-test-release:
    jobs:
    - mariadb-105:
        filters:
          tags:
            only: /.*/
    - mariadb-104:
        filters:
          tags:
            only: /.*/
#    - mariadb-104g:
#        filters:
#          tags:
#            only: /.*/
    - mariadb-103:
        filters:
          tags:
            only: /.*/
    - mariadb-102:
        filters:
          tags:
            only: /.*/
