version: 2.1
jobs:
  mariadb-103:
    # workaround https://discuss.circleci.com/t/post-clone-working-directory/15333/4
    working_directory: ~/repo/10
    machine: true
    environment:
      - MARIADB_VER: 10.3.10
      - TAGS: 10.3,10,latest
    steps:
      - checkout:
          path: ~/repo
      - run: make
      - run: make test
      - run: . ../release.sh
      - when: on_fail
        steps:
          - notify-about-failure

  mariadb-102:
    working_directory: ~/repo/10
    machine: true
    environment:
      - MARIADB_VER: 10.2.18
      - TAGS: 10.2
    steps:
      - checkout:
          path: ~/repo
      - run: make
      - run: make test
      - run: . ../release.sh
      - when: on_fail
        steps:
          - notify-about-failure

  mariadb-101:
    working_directory: ~/repo/10
    machine: true
    environment:
      - MARIADB_VER: 10.1.36
      - TAGS: 10.1
    steps:
      - checkout:
          path: ~/repo
      - run: make
      - run: make test
      - run: . ../release.sh
      - when: on_fail
        steps:
          - notify-about-failure

workflows:
  build-test-release:
    jobs:
      - mariadb-103:
          filters:
            tags:
              only: /.*/
      - mariadb-102:
          filters:
            tags:
              only: /.*/
      - mariadb-101:
          filters:
            tags:
              only: /.*/

commands:
  notify-about-failure:
    steps:
    - run:
        name: 'Notify about failure by email'
        command: |
          aws ses send-email --region us-east-1 --from $FROM_EMAIL --to $TO_EMAIL \
            --subject "MariaDB build failed" --text "${CIRCLE_BUILD_URL}"