name: Build docker image

on:
  push:
    branches:
    - master

    tags:
    - '*'

env:
  BASE_IMAGE_STABILITY_TAG: 2.6.2
  ALPINE_VER: 3.13
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  mariadb-105:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-step1-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - uses: ./.github/actions
      with:
        version: 10.5.8
        tags: 10.5,10,latest
        workdir: 10
        platform: linux/amd64,linux/arm64
  mariadb-104:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: 10.4.17
        tags: 10.4
        workdir: 10
  mariadb-103:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: 10.3.27
        tags: 10.3
        workdir: 10
  mariadb-102:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: 10.2.36
        tags: 10.2
        workdir: 10